name: NetSim CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Install GTest and CMake (just to be sure)
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        
    # Project config (Generate makefiles)
    - name: Configure CMake
      run: cmake -B build -S .

    # Project build (Compile)
    - name: Build
      run: cmake --build build

    # Run tests
    # --output-on-failure shows log only if tests fail
    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure